name: Build Check on PR

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Cache Bun Installation
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-deps-

      - name: Install Dependencies
        run: bun install

      - name: Run TypeScript type check
        run: bun run build-check
