name: Build Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: baileys-api
            image: baileys-api
            context: ./baileys-api
            dockerfile: ./baileys-api/Dockerfile
            build-args: ""
          - name: chatwoot
            image: chatwoot
            context: ./chatwoot
            dockerfile: ./chatwoot/docker/Dockerfile
            build-args: |
              RAILS_ENV=production
              BUNDLE_WITHOUT=development:test
              RAILS_SERVE_STATIC_FILES=true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:sha-${{ env.SHORT_SHA }}
          build-args: ${{ matrix.build-args }}
          provenance: false
